# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomarklint < Formula
  desc "A fast, extensible Markdown linter written in Go"
  homepage "https://github.com/shinagawa-web/gomarklint"
  version "2.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shinagawa-web/gomarklint/releases/download/v2.15.0/gomarklint_Darwin_x86_64.tar.gz"
      sha256 "9b7c731d94b1011201ef1a0f04506ce8d87b236ec07237dce688fe7f092d7818"

      define_method(:install) do
        bin.install "gomarklint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shinagawa-web/gomarklint/releases/download/v2.15.0/gomarklint_Darwin_arm64.tar.gz"
      sha256 "80da74dd074793ec9b101dc144d3cc9468f0b5993cb536cfe7650a182231ec98"

      define_method(:install) do
        bin.install "gomarklint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinagawa-web/gomarklint/releases/download/v2.15.0/gomarklint_Linux_x86_64.tar.gz"
      sha256 "8bf786d6365e58b22abf3654ca5dfbc01d14e83c9d52ffe9423a9c4b75d1450b"
      define_method(:install) do
        bin.install "gomarklint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinagawa-web/gomarklint/releases/download/v2.15.0/gomarklint_Linux_arm64.tar.gz"
      sha256 "90c5080d4c011853dfb1c22a388d30c4df60efbfebf76a0f6dfffabcba13ea71"
      define_method(:install) do
        bin.install "gomarklint"
      end
    end
  end
end
