# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgincident < Formula
  desc "Real-time PostgreSQL incident dashboard for the terminal"
  homepage "https://github.com/shinagawa-web/pgincident"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shinagawa-web/pgincident/releases/download/v0.5.1/pgincident_0.5.1_darwin_amd64.tar.gz"
      sha256 "f4c105fbb3cb3417b8a89c890e1b8538d0681e0c0746faa71a2d109246f702d7"

      define_method(:install) do
        bin.install "pgincident"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shinagawa-web/pgincident/releases/download/v0.5.1/pgincident_0.5.1_darwin_arm64.tar.gz"
      sha256 "f1ef9aafc7308be7fe95e6da714a72c6d0cf284ba1990bd424b38281e1084e19"

      define_method(:install) do
        bin.install "pgincident"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinagawa-web/pgincident/releases/download/v0.5.1/pgincident_0.5.1_linux_amd64.tar.gz"
      sha256 "d9e607e44a845593527a45834fe4001f9b382c4476236fb0c8b78366f8a9b110"
      define_method(:install) do
        bin.install "pgincident"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinagawa-web/pgincident/releases/download/v0.5.1/pgincident_0.5.1_linux_arm64.tar.gz"
      sha256 "2230c34ae298326ffc4517c1e50951a49f24a9d4f2b0445cd80132f1e7f6323b"
      define_method(:install) do
        bin.install "pgincident"
      end
    end
  end

  test do
    system "#{bin}/pgincident", "--version"
  end
end
