# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgincident < Formula
  desc "Real-time PostgreSQL incident dashboard for the terminal"
  homepage "https://github.com/shinagawa-web/pgincident"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shinagawa-web/pgincident/releases/download/v0.6.0/pgincident_0.6.0_darwin_amd64.tar.gz"
      sha256 "c5e25267b0333bd100baa865da591ddcecc6cb5d8d2a7dc2ff07ed83403c3ee5"

      define_method(:install) do
        bin.install "pgincident"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shinagawa-web/pgincident/releases/download/v0.6.0/pgincident_0.6.0_darwin_arm64.tar.gz"
      sha256 "86d8e08a4cfe38179200c977cb6dd5f2dabbff615a4ee1f7b82a1f46c3999763"

      define_method(:install) do
        bin.install "pgincident"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinagawa-web/pgincident/releases/download/v0.6.0/pgincident_0.6.0_linux_amd64.tar.gz"
      sha256 "de8cc11a68f58c5e514a05cce0e8f3d56bb11d0bb311bfc05e58de74e9a709b8"
      define_method(:install) do
        bin.install "pgincident"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinagawa-web/pgincident/releases/download/v0.6.0/pgincident_0.6.0_linux_arm64.tar.gz"
      sha256 "9720192f029f4eb07dc6a4de962869ae54cd4354cd90388655d105e826a7c135"
      define_method(:install) do
        bin.install "pgincident"
      end
    end
  end

  test do
    system "#{bin}/pgincident", "--version"
  end
end
